<?php
/**
 * EditRepoOption
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Efsa\Client\Gitea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.17.0+dev-334-gf36701c70
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Efsa\Client\Gitea\Model;

use \ArrayAccess;
use \Efsa\Client\Gitea\ObjectSerializer;

/**
 * EditRepoOption Class Doc Comment
 *
 * @category Class
 * @description EditRepoOption options when editing a repository&#39;s properties
 * @package  Efsa\Client\Gitea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class EditRepoOption implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EditRepoOption';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'allowManualMerge' => 'bool',
        'allowMergeCommits' => 'bool',
        'allowRebase' => 'bool',
        'allowRebaseExplicit' => 'bool',
        'allowRebaseUpdate' => 'bool',
        'allowSquashMerge' => 'bool',
        'archived' => 'bool',
        'autodetectManualMerge' => 'bool',
        'defaultBranch' => 'string',
        'defaultDeleteBranchAfterMerge' => 'bool',
        'defaultMergeStyle' => 'string',
        'description' => 'string',
        'externalTracker' => '\Efsa\Client\Gitea\Model\ExternalTracker',
        'externalWiki' => '\Efsa\Client\Gitea\Model\ExternalWiki',
        'hasIssues' => 'bool',
        'hasProjects' => 'bool',
        'hasPullRequests' => 'bool',
        'hasWiki' => 'bool',
        'ignoreWhitespaceConflicts' => 'bool',
        'internalTracker' => '\Efsa\Client\Gitea\Model\InternalTracker',
        'mirrorInterval' => 'string',
        'name' => 'string',
        'private' => 'bool',
        'template' => 'bool',
        'website' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'allowManualMerge' => null,
        'allowMergeCommits' => null,
        'allowRebase' => null,
        'allowRebaseExplicit' => null,
        'allowRebaseUpdate' => null,
        'allowSquashMerge' => null,
        'archived' => null,
        'autodetectManualMerge' => null,
        'defaultBranch' => null,
        'defaultDeleteBranchAfterMerge' => null,
        'defaultMergeStyle' => null,
        'description' => null,
        'externalTracker' => null,
        'externalWiki' => null,
        'hasIssues' => null,
        'hasProjects' => null,
        'hasPullRequests' => null,
        'hasWiki' => null,
        'ignoreWhitespaceConflicts' => null,
        'internalTracker' => null,
        'mirrorInterval' => null,
        'name' => null,
        'private' => null,
        'template' => null,
        'website' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'allowManualMerge' => 'allow_manual_merge',
        'allowMergeCommits' => 'allow_merge_commits',
        'allowRebase' => 'allow_rebase',
        'allowRebaseExplicit' => 'allow_rebase_explicit',
        'allowRebaseUpdate' => 'allow_rebase_update',
        'allowSquashMerge' => 'allow_squash_merge',
        'archived' => 'archived',
        'autodetectManualMerge' => 'autodetect_manual_merge',
        'defaultBranch' => 'default_branch',
        'defaultDeleteBranchAfterMerge' => 'default_delete_branch_after_merge',
        'defaultMergeStyle' => 'default_merge_style',
        'description' => 'description',
        'externalTracker' => 'external_tracker',
        'externalWiki' => 'external_wiki',
        'hasIssues' => 'has_issues',
        'hasProjects' => 'has_projects',
        'hasPullRequests' => 'has_pull_requests',
        'hasWiki' => 'has_wiki',
        'ignoreWhitespaceConflicts' => 'ignore_whitespace_conflicts',
        'internalTracker' => 'internal_tracker',
        'mirrorInterval' => 'mirror_interval',
        'name' => 'name',
        'private' => 'private',
        'template' => 'template',
        'website' => 'website'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'allowManualMerge' => 'setAllowManualMerge',
        'allowMergeCommits' => 'setAllowMergeCommits',
        'allowRebase' => 'setAllowRebase',
        'allowRebaseExplicit' => 'setAllowRebaseExplicit',
        'allowRebaseUpdate' => 'setAllowRebaseUpdate',
        'allowSquashMerge' => 'setAllowSquashMerge',
        'archived' => 'setArchived',
        'autodetectManualMerge' => 'setAutodetectManualMerge',
        'defaultBranch' => 'setDefaultBranch',
        'defaultDeleteBranchAfterMerge' => 'setDefaultDeleteBranchAfterMerge',
        'defaultMergeStyle' => 'setDefaultMergeStyle',
        'description' => 'setDescription',
        'externalTracker' => 'setExternalTracker',
        'externalWiki' => 'setExternalWiki',
        'hasIssues' => 'setHasIssues',
        'hasProjects' => 'setHasProjects',
        'hasPullRequests' => 'setHasPullRequests',
        'hasWiki' => 'setHasWiki',
        'ignoreWhitespaceConflicts' => 'setIgnoreWhitespaceConflicts',
        'internalTracker' => 'setInternalTracker',
        'mirrorInterval' => 'setMirrorInterval',
        'name' => 'setName',
        'private' => 'setPrivate',
        'template' => 'setTemplate',
        'website' => 'setWebsite'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'allowManualMerge' => 'getAllowManualMerge',
        'allowMergeCommits' => 'getAllowMergeCommits',
        'allowRebase' => 'getAllowRebase',
        'allowRebaseExplicit' => 'getAllowRebaseExplicit',
        'allowRebaseUpdate' => 'getAllowRebaseUpdate',
        'allowSquashMerge' => 'getAllowSquashMerge',
        'archived' => 'getArchived',
        'autodetectManualMerge' => 'getAutodetectManualMerge',
        'defaultBranch' => 'getDefaultBranch',
        'defaultDeleteBranchAfterMerge' => 'getDefaultDeleteBranchAfterMerge',
        'defaultMergeStyle' => 'getDefaultMergeStyle',
        'description' => 'getDescription',
        'externalTracker' => 'getExternalTracker',
        'externalWiki' => 'getExternalWiki',
        'hasIssues' => 'getHasIssues',
        'hasProjects' => 'getHasProjects',
        'hasPullRequests' => 'getHasPullRequests',
        'hasWiki' => 'getHasWiki',
        'ignoreWhitespaceConflicts' => 'getIgnoreWhitespaceConflicts',
        'internalTracker' => 'getInternalTracker',
        'mirrorInterval' => 'getMirrorInterval',
        'name' => 'getName',
        'private' => 'getPrivate',
        'template' => 'getTemplate',
        'website' => 'getWebsite'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['allowManualMerge'] = $data['allowManualMerge'] ?? null;
        $this->container['allowMergeCommits'] = $data['allowMergeCommits'] ?? null;
        $this->container['allowRebase'] = $data['allowRebase'] ?? null;
        $this->container['allowRebaseExplicit'] = $data['allowRebaseExplicit'] ?? null;
        $this->container['allowRebaseUpdate'] = $data['allowRebaseUpdate'] ?? null;
        $this->container['allowSquashMerge'] = $data['allowSquashMerge'] ?? null;
        $this->container['archived'] = $data['archived'] ?? null;
        $this->container['autodetectManualMerge'] = $data['autodetectManualMerge'] ?? null;
        $this->container['defaultBranch'] = $data['defaultBranch'] ?? null;
        $this->container['defaultDeleteBranchAfterMerge'] = $data['defaultDeleteBranchAfterMerge'] ?? null;
        $this->container['defaultMergeStyle'] = $data['defaultMergeStyle'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
        $this->container['externalTracker'] = $data['externalTracker'] ?? null;
        $this->container['externalWiki'] = $data['externalWiki'] ?? null;
        $this->container['hasIssues'] = $data['hasIssues'] ?? null;
        $this->container['hasProjects'] = $data['hasProjects'] ?? null;
        $this->container['hasPullRequests'] = $data['hasPullRequests'] ?? null;
        $this->container['hasWiki'] = $data['hasWiki'] ?? null;
        $this->container['ignoreWhitespaceConflicts'] = $data['ignoreWhitespaceConflicts'] ?? null;
        $this->container['internalTracker'] = $data['internalTracker'] ?? null;
        $this->container['mirrorInterval'] = $data['mirrorInterval'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['private'] = $data['private'] ?? null;
        $this->container['template'] = $data['template'] ?? null;
        $this->container['website'] = $data['website'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets allowManualMerge
     *
     * @return bool|null
     */
    public function getAllowManualMerge()
    {
        return $this->container['allowManualMerge'];
    }

    /**
     * Sets allowManualMerge
     *
     * @param bool|null $allowManualMerge either `true` to allow mark pr as merged manually, or `false` to prevent it. `has_pull_requests` must be `true`.
     *
     * @return self
     */
    public function setAllowManualMerge($allowManualMerge)
    {
        $this->container['allowManualMerge'] = $allowManualMerge;

        return $this;
    }

    /**
     * Gets allowMergeCommits
     *
     * @return bool|null
     */
    public function getAllowMergeCommits()
    {
        return $this->container['allowMergeCommits'];
    }

    /**
     * Sets allowMergeCommits
     *
     * @param bool|null $allowMergeCommits either `true` to allow merging pull requests with a merge commit, or `false` to prevent merging pull requests with merge commits. `has_pull_requests` must be `true`.
     *
     * @return self
     */
    public function setAllowMergeCommits($allowMergeCommits)
    {
        $this->container['allowMergeCommits'] = $allowMergeCommits;

        return $this;
    }

    /**
     * Gets allowRebase
     *
     * @return bool|null
     */
    public function getAllowRebase()
    {
        return $this->container['allowRebase'];
    }

    /**
     * Sets allowRebase
     *
     * @param bool|null $allowRebase either `true` to allow rebase-merging pull requests, or `false` to prevent rebase-merging. `has_pull_requests` must be `true`.
     *
     * @return self
     */
    public function setAllowRebase($allowRebase)
    {
        $this->container['allowRebase'] = $allowRebase;

        return $this;
    }

    /**
     * Gets allowRebaseExplicit
     *
     * @return bool|null
     */
    public function getAllowRebaseExplicit()
    {
        return $this->container['allowRebaseExplicit'];
    }

    /**
     * Sets allowRebaseExplicit
     *
     * @param bool|null $allowRebaseExplicit either `true` to allow rebase with explicit merge commits (--no-ff), or `false` to prevent rebase with explicit merge commits. `has_pull_requests` must be `true`.
     *
     * @return self
     */
    public function setAllowRebaseExplicit($allowRebaseExplicit)
    {
        $this->container['allowRebaseExplicit'] = $allowRebaseExplicit;

        return $this;
    }

    /**
     * Gets allowRebaseUpdate
     *
     * @return bool|null
     */
    public function getAllowRebaseUpdate()
    {
        return $this->container['allowRebaseUpdate'];
    }

    /**
     * Sets allowRebaseUpdate
     *
     * @param bool|null $allowRebaseUpdate either `true` to allow updating pull request branch by rebase, or `false` to prevent it. `has_pull_requests` must be `true`.
     *
     * @return self
     */
    public function setAllowRebaseUpdate($allowRebaseUpdate)
    {
        $this->container['allowRebaseUpdate'] = $allowRebaseUpdate;

        return $this;
    }

    /**
     * Gets allowSquashMerge
     *
     * @return bool|null
     */
    public function getAllowSquashMerge()
    {
        return $this->container['allowSquashMerge'];
    }

    /**
     * Sets allowSquashMerge
     *
     * @param bool|null $allowSquashMerge either `true` to allow squash-merging pull requests, or `false` to prevent squash-merging. `has_pull_requests` must be `true`.
     *
     * @return self
     */
    public function setAllowSquashMerge($allowSquashMerge)
    {
        $this->container['allowSquashMerge'] = $allowSquashMerge;

        return $this;
    }

    /**
     * Gets archived
     *
     * @return bool|null
     */
    public function getArchived()
    {
        return $this->container['archived'];
    }

    /**
     * Sets archived
     *
     * @param bool|null $archived set to `true` to archive this repository.
     *
     * @return self
     */
    public function setArchived($archived)
    {
        $this->container['archived'] = $archived;

        return $this;
    }

    /**
     * Gets autodetectManualMerge
     *
     * @return bool|null
     */
    public function getAutodetectManualMerge()
    {
        return $this->container['autodetectManualMerge'];
    }

    /**
     * Sets autodetectManualMerge
     *
     * @param bool|null $autodetectManualMerge either `true` to enable AutodetectManualMerge, or `false` to prevent it. `has_pull_requests` must be `true`, Note: In some special cases, misjudgments can occur.
     *
     * @return self
     */
    public function setAutodetectManualMerge($autodetectManualMerge)
    {
        $this->container['autodetectManualMerge'] = $autodetectManualMerge;

        return $this;
    }

    /**
     * Gets defaultBranch
     *
     * @return string|null
     */
    public function getDefaultBranch()
    {
        return $this->container['defaultBranch'];
    }

    /**
     * Sets defaultBranch
     *
     * @param string|null $defaultBranch sets the default branch for this repository.
     *
     * @return self
     */
    public function setDefaultBranch($defaultBranch)
    {
        $this->container['defaultBranch'] = $defaultBranch;

        return $this;
    }

    /**
     * Gets defaultDeleteBranchAfterMerge
     *
     * @return bool|null
     */
    public function getDefaultDeleteBranchAfterMerge()
    {
        return $this->container['defaultDeleteBranchAfterMerge'];
    }

    /**
     * Sets defaultDeleteBranchAfterMerge
     *
     * @param bool|null $defaultDeleteBranchAfterMerge set to `true` to delete pr branch after merge by default
     *
     * @return self
     */
    public function setDefaultDeleteBranchAfterMerge($defaultDeleteBranchAfterMerge)
    {
        $this->container['defaultDeleteBranchAfterMerge'] = $defaultDeleteBranchAfterMerge;

        return $this;
    }

    /**
     * Gets defaultMergeStyle
     *
     * @return string|null
     */
    public function getDefaultMergeStyle()
    {
        return $this->container['defaultMergeStyle'];
    }

    /**
     * Sets defaultMergeStyle
     *
     * @param string|null $defaultMergeStyle set to a merge style to be used by this repository: \"merge\", \"rebase\", \"rebase-merge\", or \"squash\". `has_pull_requests` must be `true`.
     *
     * @return self
     */
    public function setDefaultMergeStyle($defaultMergeStyle)
    {
        $this->container['defaultMergeStyle'] = $defaultMergeStyle;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description a short description of the repository.
     *
     * @return self
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets externalTracker
     *
     * @return \Efsa\Client\Gitea\Model\ExternalTracker|null
     */
    public function getExternalTracker()
    {
        return $this->container['externalTracker'];
    }

    /**
     * Sets externalTracker
     *
     * @param \Efsa\Client\Gitea\Model\ExternalTracker|null $externalTracker externalTracker
     *
     * @return self
     */
    public function setExternalTracker($externalTracker)
    {
        $this->container['externalTracker'] = $externalTracker;

        return $this;
    }

    /**
     * Gets externalWiki
     *
     * @return \Efsa\Client\Gitea\Model\ExternalWiki|null
     */
    public function getExternalWiki()
    {
        return $this->container['externalWiki'];
    }

    /**
     * Sets externalWiki
     *
     * @param \Efsa\Client\Gitea\Model\ExternalWiki|null $externalWiki externalWiki
     *
     * @return self
     */
    public function setExternalWiki($externalWiki)
    {
        $this->container['externalWiki'] = $externalWiki;

        return $this;
    }

    /**
     * Gets hasIssues
     *
     * @return bool|null
     */
    public function getHasIssues()
    {
        return $this->container['hasIssues'];
    }

    /**
     * Sets hasIssues
     *
     * @param bool|null $hasIssues either `true` to enable issues for this repository or `false` to disable them.
     *
     * @return self
     */
    public function setHasIssues($hasIssues)
    {
        $this->container['hasIssues'] = $hasIssues;

        return $this;
    }

    /**
     * Gets hasProjects
     *
     * @return bool|null
     */
    public function getHasProjects()
    {
        return $this->container['hasProjects'];
    }

    /**
     * Sets hasProjects
     *
     * @param bool|null $hasProjects either `true` to enable project unit, or `false` to disable them.
     *
     * @return self
     */
    public function setHasProjects($hasProjects)
    {
        $this->container['hasProjects'] = $hasProjects;

        return $this;
    }

    /**
     * Gets hasPullRequests
     *
     * @return bool|null
     */
    public function getHasPullRequests()
    {
        return $this->container['hasPullRequests'];
    }

    /**
     * Sets hasPullRequests
     *
     * @param bool|null $hasPullRequests either `true` to allow pull requests, or `false` to prevent pull request.
     *
     * @return self
     */
    public function setHasPullRequests($hasPullRequests)
    {
        $this->container['hasPullRequests'] = $hasPullRequests;

        return $this;
    }

    /**
     * Gets hasWiki
     *
     * @return bool|null
     */
    public function getHasWiki()
    {
        return $this->container['hasWiki'];
    }

    /**
     * Sets hasWiki
     *
     * @param bool|null $hasWiki either `true` to enable the wiki for this repository or `false` to disable it.
     *
     * @return self
     */
    public function setHasWiki($hasWiki)
    {
        $this->container['hasWiki'] = $hasWiki;

        return $this;
    }

    /**
     * Gets ignoreWhitespaceConflicts
     *
     * @return bool|null
     */
    public function getIgnoreWhitespaceConflicts()
    {
        return $this->container['ignoreWhitespaceConflicts'];
    }

    /**
     * Sets ignoreWhitespaceConflicts
     *
     * @param bool|null $ignoreWhitespaceConflicts either `true` to ignore whitespace for conflicts, or `false` to not ignore whitespace. `has_pull_requests` must be `true`.
     *
     * @return self
     */
    public function setIgnoreWhitespaceConflicts($ignoreWhitespaceConflicts)
    {
        $this->container['ignoreWhitespaceConflicts'] = $ignoreWhitespaceConflicts;

        return $this;
    }

    /**
     * Gets internalTracker
     *
     * @return \Efsa\Client\Gitea\Model\InternalTracker|null
     */
    public function getInternalTracker()
    {
        return $this->container['internalTracker'];
    }

    /**
     * Sets internalTracker
     *
     * @param \Efsa\Client\Gitea\Model\InternalTracker|null $internalTracker internalTracker
     *
     * @return self
     */
    public function setInternalTracker($internalTracker)
    {
        $this->container['internalTracker'] = $internalTracker;

        return $this;
    }

    /**
     * Gets mirrorInterval
     *
     * @return string|null
     */
    public function getMirrorInterval()
    {
        return $this->container['mirrorInterval'];
    }

    /**
     * Sets mirrorInterval
     *
     * @param string|null $mirrorInterval set to a string like `8h30m0s` to set the mirror interval time
     *
     * @return self
     */
    public function setMirrorInterval($mirrorInterval)
    {
        $this->container['mirrorInterval'] = $mirrorInterval;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name of the repository
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets private
     *
     * @return bool|null
     */
    public function getPrivate()
    {
        return $this->container['private'];
    }

    /**
     * Sets private
     *
     * @param bool|null $private either `true` to make the repository private or `false` to make it public. Note: you will get a 422 error if the organization restricts changing repository visibility to organization owners and a non-owner tries to change the value of private.
     *
     * @return self
     */
    public function setPrivate($private)
    {
        $this->container['private'] = $private;

        return $this;
    }

    /**
     * Gets template
     *
     * @return bool|null
     */
    public function getTemplate()
    {
        return $this->container['template'];
    }

    /**
     * Sets template
     *
     * @param bool|null $template either `true` to make this repository a template or `false` to make it a normal repository
     *
     * @return self
     */
    public function setTemplate($template)
    {
        $this->container['template'] = $template;

        return $this;
    }

    /**
     * Gets website
     *
     * @return string|null
     */
    public function getWebsite()
    {
        return $this->container['website'];
    }

    /**
     * Sets website
     *
     * @param string|null $website a URL with more information about the repository.
     *
     * @return self
     */
    public function setWebsite($website)
    {
        $this->container['website'] = $website;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


