<?php
/**
 * PullReviewComment
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Efsa\Client\Gitea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.17.0+dev-334-gf36701c70
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Efsa\Client\Gitea\Model;

use \ArrayAccess;
use \Efsa\Client\Gitea\ObjectSerializer;

/**
 * PullReviewComment Class Doc Comment
 *
 * @category Class
 * @description PullReviewComment represents a comment on a pull request review
 * @package  Efsa\Client\Gitea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class PullReviewComment implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PullReviewComment';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'body' => 'string',
        'commitId' => 'string',
        'createdAt' => '\DateTime',
        'diffHunk' => 'string',
        'htmlUrl' => 'string',
        'id' => 'int',
        'originalCommitId' => 'string',
        'originalPosition' => 'int',
        'path' => 'string',
        'position' => 'int',
        'pullRequestReviewId' => 'int',
        'pullRequestUrl' => 'string',
        'resolver' => '\Efsa\Client\Gitea\Model\User',
        'updatedAt' => '\DateTime',
        'user' => '\Efsa\Client\Gitea\Model\User'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'body' => null,
        'commitId' => null,
        'createdAt' => 'date-time',
        'diffHunk' => null,
        'htmlUrl' => null,
        'id' => 'int64',
        'originalCommitId' => null,
        'originalPosition' => 'uint64',
        'path' => null,
        'position' => 'uint64',
        'pullRequestReviewId' => 'int64',
        'pullRequestUrl' => null,
        'resolver' => null,
        'updatedAt' => 'date-time',
        'user' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'body' => 'body',
        'commitId' => 'commit_id',
        'createdAt' => 'created_at',
        'diffHunk' => 'diff_hunk',
        'htmlUrl' => 'html_url',
        'id' => 'id',
        'originalCommitId' => 'original_commit_id',
        'originalPosition' => 'original_position',
        'path' => 'path',
        'position' => 'position',
        'pullRequestReviewId' => 'pull_request_review_id',
        'pullRequestUrl' => 'pull_request_url',
        'resolver' => 'resolver',
        'updatedAt' => 'updated_at',
        'user' => 'user'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'body' => 'setBody',
        'commitId' => 'setCommitId',
        'createdAt' => 'setCreatedAt',
        'diffHunk' => 'setDiffHunk',
        'htmlUrl' => 'setHtmlUrl',
        'id' => 'setId',
        'originalCommitId' => 'setOriginalCommitId',
        'originalPosition' => 'setOriginalPosition',
        'path' => 'setPath',
        'position' => 'setPosition',
        'pullRequestReviewId' => 'setPullRequestReviewId',
        'pullRequestUrl' => 'setPullRequestUrl',
        'resolver' => 'setResolver',
        'updatedAt' => 'setUpdatedAt',
        'user' => 'setUser'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'body' => 'getBody',
        'commitId' => 'getCommitId',
        'createdAt' => 'getCreatedAt',
        'diffHunk' => 'getDiffHunk',
        'htmlUrl' => 'getHtmlUrl',
        'id' => 'getId',
        'originalCommitId' => 'getOriginalCommitId',
        'originalPosition' => 'getOriginalPosition',
        'path' => 'getPath',
        'position' => 'getPosition',
        'pullRequestReviewId' => 'getPullRequestReviewId',
        'pullRequestUrl' => 'getPullRequestUrl',
        'resolver' => 'getResolver',
        'updatedAt' => 'getUpdatedAt',
        'user' => 'getUser'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['body'] = $data['body'] ?? null;
        $this->container['commitId'] = $data['commitId'] ?? null;
        $this->container['createdAt'] = $data['createdAt'] ?? null;
        $this->container['diffHunk'] = $data['diffHunk'] ?? null;
        $this->container['htmlUrl'] = $data['htmlUrl'] ?? null;
        $this->container['id'] = $data['id'] ?? null;
        $this->container['originalCommitId'] = $data['originalCommitId'] ?? null;
        $this->container['originalPosition'] = $data['originalPosition'] ?? null;
        $this->container['path'] = $data['path'] ?? null;
        $this->container['position'] = $data['position'] ?? null;
        $this->container['pullRequestReviewId'] = $data['pullRequestReviewId'] ?? null;
        $this->container['pullRequestUrl'] = $data['pullRequestUrl'] ?? null;
        $this->container['resolver'] = $data['resolver'] ?? null;
        $this->container['updatedAt'] = $data['updatedAt'] ?? null;
        $this->container['user'] = $data['user'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets body
     *
     * @return string|null
     */
    public function getBody()
    {
        return $this->container['body'];
    }

    /**
     * Sets body
     *
     * @param string|null $body body
     *
     * @return self
     */
    public function setBody($body)
    {
        $this->container['body'] = $body;

        return $this;
    }

    /**
     * Gets commitId
     *
     * @return string|null
     */
    public function getCommitId()
    {
        return $this->container['commitId'];
    }

    /**
     * Sets commitId
     *
     * @param string|null $commitId commitId
     *
     * @return self
     */
    public function setCommitId($commitId)
    {
        $this->container['commitId'] = $commitId;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime|null $createdAt createdAt
     *
     * @return self
     */
    public function setCreatedAt($createdAt)
    {
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets diffHunk
     *
     * @return string|null
     */
    public function getDiffHunk()
    {
        return $this->container['diffHunk'];
    }

    /**
     * Sets diffHunk
     *
     * @param string|null $diffHunk diffHunk
     *
     * @return self
     */
    public function setDiffHunk($diffHunk)
    {
        $this->container['diffHunk'] = $diffHunk;

        return $this;
    }

    /**
     * Gets htmlUrl
     *
     * @return string|null
     */
    public function getHtmlUrl()
    {
        return $this->container['htmlUrl'];
    }

    /**
     * Sets htmlUrl
     *
     * @param string|null $htmlUrl htmlUrl
     *
     * @return self
     */
    public function setHtmlUrl($htmlUrl)
    {
        $this->container['htmlUrl'] = $htmlUrl;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets originalCommitId
     *
     * @return string|null
     */
    public function getOriginalCommitId()
    {
        return $this->container['originalCommitId'];
    }

    /**
     * Sets originalCommitId
     *
     * @param string|null $originalCommitId originalCommitId
     *
     * @return self
     */
    public function setOriginalCommitId($originalCommitId)
    {
        $this->container['originalCommitId'] = $originalCommitId;

        return $this;
    }

    /**
     * Gets originalPosition
     *
     * @return int|null
     */
    public function getOriginalPosition()
    {
        return $this->container['originalPosition'];
    }

    /**
     * Sets originalPosition
     *
     * @param int|null $originalPosition originalPosition
     *
     * @return self
     */
    public function setOriginalPosition($originalPosition)
    {
        $this->container['originalPosition'] = $originalPosition;

        return $this;
    }

    /**
     * Gets path
     *
     * @return string|null
     */
    public function getPath()
    {
        return $this->container['path'];
    }

    /**
     * Sets path
     *
     * @param string|null $path path
     *
     * @return self
     */
    public function setPath($path)
    {
        $this->container['path'] = $path;

        return $this;
    }

    /**
     * Gets position
     *
     * @return int|null
     */
    public function getPosition()
    {
        return $this->container['position'];
    }

    /**
     * Sets position
     *
     * @param int|null $position position
     *
     * @return self
     */
    public function setPosition($position)
    {
        $this->container['position'] = $position;

        return $this;
    }

    /**
     * Gets pullRequestReviewId
     *
     * @return int|null
     */
    public function getPullRequestReviewId()
    {
        return $this->container['pullRequestReviewId'];
    }

    /**
     * Sets pullRequestReviewId
     *
     * @param int|null $pullRequestReviewId pullRequestReviewId
     *
     * @return self
     */
    public function setPullRequestReviewId($pullRequestReviewId)
    {
        $this->container['pullRequestReviewId'] = $pullRequestReviewId;

        return $this;
    }

    /**
     * Gets pullRequestUrl
     *
     * @return string|null
     */
    public function getPullRequestUrl()
    {
        return $this->container['pullRequestUrl'];
    }

    /**
     * Sets pullRequestUrl
     *
     * @param string|null $pullRequestUrl pullRequestUrl
     *
     * @return self
     */
    public function setPullRequestUrl($pullRequestUrl)
    {
        $this->container['pullRequestUrl'] = $pullRequestUrl;

        return $this;
    }

    /**
     * Gets resolver
     *
     * @return \Efsa\Client\Gitea\Model\User|null
     */
    public function getResolver()
    {
        return $this->container['resolver'];
    }

    /**
     * Sets resolver
     *
     * @param \Efsa\Client\Gitea\Model\User|null $resolver resolver
     *
     * @return self
     */
    public function setResolver($resolver)
    {
        $this->container['resolver'] = $resolver;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param \DateTime|null $updatedAt updatedAt
     *
     * @return self
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }

    /**
     * Gets user
     *
     * @return \Efsa\Client\Gitea\Model\User|null
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param \Efsa\Client\Gitea\Model\User|null $user user
     *
     * @return self
     */
    public function setUser($user)
    {
        $this->container['user'] = $user;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


