<?php
/**
 * BranchTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Efsa\Client\Gitea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.17.0+dev-334-gf36701c70
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Efsa\Client\Gitea\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BranchTest Class Doc Comment
 *
 * @category    Class
 * @description Branch represents a repository branch
 * @package     Efsa\Client\Gitea
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BranchTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Branch"
     */
    public function testBranch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "commit"
     */
    public function testPropertyCommit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "effectiveBranchProtectionName"
     */
    public function testPropertyEffectiveBranchProtectionName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "enableStatusCheck"
     */
    public function testPropertyEnableStatusCheck()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "protected"
     */
    public function testPropertyProtected()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "requiredApprovals"
     */
    public function testPropertyRequiredApprovals()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "statusCheckContexts"
     */
    public function testPropertyStatusCheckContexts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "userCanMerge"
     */
    public function testPropertyUserCanMerge()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "userCanPush"
     */
    public function testPropertyUserCanPush()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
