<?php
/**
 * AdminApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Efsa\Client\Gitea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.17.0+dev-334-gf36701c70
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Efsa\Client\Gitea\Test\Api;

use \Efsa\Client\Gitea\Configuration;
use \Efsa\Client\Gitea\ApiException;
use \Efsa\Client\Gitea\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AdminApiTest Class Doc Comment
 *
 * @category Class
 * @package  Efsa\Client\Gitea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdminApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for adminAdoptRepository
     *
     * Adopt unadopted files as a repository.
     *
     */
    public function testAdminAdoptRepository()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminCreateOrg
     *
     * Create an organization.
     *
     */
    public function testAdminCreateOrg()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminCreatePublicKey
     *
     * Add a public key on behalf of a user.
     *
     */
    public function testAdminCreatePublicKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminCreateRepo
     *
     * Create a repository on behalf of a user.
     *
     */
    public function testAdminCreateRepo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminCreateUser
     *
     * Create a user.
     *
     */
    public function testAdminCreateUser()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminCronList
     *
     * List cron tasks.
     *
     */
    public function testAdminCronList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminCronRun
     *
     * Run cron task.
     *
     */
    public function testAdminCronRun()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminDeleteUnadoptedRepository
     *
     * Delete unadopted files.
     *
     */
    public function testAdminDeleteUnadoptedRepository()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminDeleteUser
     *
     * Delete a user.
     *
     */
    public function testAdminDeleteUser()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminDeleteUserPublicKey
     *
     * Delete a user's public key.
     *
     */
    public function testAdminDeleteUserPublicKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminEditUser
     *
     * Edit an existing user.
     *
     */
    public function testAdminEditUser()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminGetAllOrgs
     *
     * List all organizations.
     *
     */
    public function testAdminGetAllOrgs()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminGetAllUsers
     *
     * List all users.
     *
     */
    public function testAdminGetAllUsers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for adminUnadoptedList
     *
     * List unadopted repositories.
     *
     */
    public function testAdminUnadoptedList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
