<?php
/**
 * MiscellaneousApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  \Efsa\Client\Gitea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.17.0+dev-334-gf36701c70
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace \Efsa\Client\Gitea\Test\Api;

use \\Efsa\Client\Gitea\Configuration;
use \\Efsa\Client\Gitea\ApiException;
use \\Efsa\Client\Gitea\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MiscellaneousApiTest Class Doc Comment
 *
 * @category Class
 * @package  \Efsa\Client\Gitea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MiscellaneousApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getNodeInfo
     *
     * Returns the nodeinfo of the Gitea application.
     *
     */
    public function testGetNodeInfo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSigningKey
     *
     * Get default signing-key.gpg.
     *
     */
    public function testGetSigningKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getVersion
     *
     * Returns the version of the Gitea application.
     *
     */
    public function testGetVersion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for renderMarkdown
     *
     * Render a markdown document as HTML.
     *
     */
    public function testRenderMarkdown()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for renderMarkdownRaw
     *
     * Render raw markdown as HTML.
     *
     */
    public function testRenderMarkdownRaw()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
