<?php
/**
 * NotificationApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  \Efsa\Client\Gitea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.17.0+dev-334-gf36701c70
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace \Efsa\Client\Gitea\Test\Api;

use \\Efsa\Client\Gitea\Configuration;
use \\Efsa\Client\Gitea\ApiException;
use \\Efsa\Client\Gitea\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * NotificationApiTest Class Doc Comment
 *
 * @category Class
 * @package  \Efsa\Client\Gitea
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NotificationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for notifyGetList
     *
     * List users's notification threads.
     *
     */
    public function testNotifyGetList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for notifyGetRepoList
     *
     * List users's notification threads on a specific repo.
     *
     */
    public function testNotifyGetRepoList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for notifyGetThread
     *
     * Get notification thread by ID.
     *
     */
    public function testNotifyGetThread()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for notifyNewAvailable
     *
     * Check if unread notifications exist.
     *
     */
    public function testNotifyNewAvailable()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for notifyReadList
     *
     * Mark notification threads as read, pinned or unread.
     *
     */
    public function testNotifyReadList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for notifyReadRepoList
     *
     * Mark notification threads as read, pinned or unread on a specific repo.
     *
     */
    public function testNotifyReadRepoList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for notifyReadThread
     *
     * Mark notification thread as read by ID.
     *
     */
    public function testNotifyReadThread()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
